# Generated by Django 4.2.14 on 2024-07-30 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uid', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('productName', models.CharField(default='unknown', max_length=30)),
                ('productType', models.CharField(default='unknown', max_length=30)),
                ('productDescription', models.CharField(default='unknown', max_length=100)),
                ('productPrice', models.DecimalField(decimal_places=2, default='unknown', max_digits=5)),
                ('sellerId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('streetName', models.CharField(max_length=20)),
                ('landMark', models.CharField(max_length=20)),
                ('postalCode', models.DecimalField(decimal_places=0, max_digits=6)),
                ('default', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
