# Generated by Django 4.2.14 on 2024-07-30 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agroFarm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('streetName', models.CharField(max_length=20)),
                ('landMark', models.CharField(max_length=20)),
                ('postalCode', models.DecimalField(decimal_places=0, max_digits=6)),
                ('default', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='featuredimage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sellerid',
        ),
        migrations.AddField(
            model_name='product',
            name='productDescription',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='productName',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='productPrice',
            field=models.DecimalField(decimal_places=2, default='unknown', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='productType',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='product',
            name='sellerId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
