# Generated by Django 4.2.14 on 2024-08-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroFarm', '0002_alter_product_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featuredimage',
            field=models.ImageField(default=0, upload_to='uploads/'),
        ),
    ]
