# Generated by Django 4.2.14 on 2024-08-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroFarm', '0007_alter_municipality_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
