# Generated by Django 4.2.14 on 2024-08-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroFarm', '0008_alter_producttype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productType',
        ),
        migrations.AddField(
            model_name='product',
            name='productType',
            field=models.ManyToManyField(default=0, to='agroFarm.producttype'),
        ),
    ]
