# Generated by Django 4.2.14 on 2024-08-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroFarm', '0009_remove_product_producttype_product_producttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='country',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='district',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
    ]
