# Generated by Django 4.2.14 on 2024-08-10 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agroFarm', '0011_country_district_province_municipality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='postalCode',
            field=models.DecimalField(decimal_places=0, default='unknown', max_digits=10),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
