# Generated by Django 4.2.14 on 2024-08-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroFarm', '0012_alter_billingaddress_postalcode_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Municipality',
        ),
    ]
