# Generated by Django 4.2.14 on 2024-08-10 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agroFarm', '0013_delete_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroFarm.country'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroFarm.district'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroFarm.province'),
        ),
    ]
