# Generated by Django 4.2.14 on 2024-08-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroFarm', '0014_alter_billingaddress_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='postalCode',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
